### ISSUE TITLE
How do you register MCP servers with this proxy?

### ISSUE THREAD

**Issue by muliyul** [metatool-ai/mcp-server-metamcp#14]
I've deployed `metatool-web` and `metamcp-server` and set the api key to the one from `metatool-web` but I can't figure out how to proxy other servers with this.

`metatool-web` runs in a container on port 12005.

`metamcp-server` runs in a container with a modified Dockerfile for SSE:
```Dockerfile
ENTRYPOINT ["node", "dist/index.js", "--transport" , "sse", "--port", "12006"]
```

It is unclear for me how to go from here.

**Comment by zhjch05** [comment]
The line you shared looks correct. You need to make sure env vars are correctly set in the docker container METAMCP_API_KEY and METAMCP_API_BASE_URL, especially the url cannot be localhost because it is in docker, try host.docker.internal instead of localhost

**Comment by muliyul** [comment]
The env is set up with a `.env` file included in the compose setup I have.
```yaml
services:
  metatool-web:
    container_name: metatool-web
    build:
      context: apps/metatool-app
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - '12005:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - metatool-postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      mcp-network:

  metatool-postgres:
    container_name: metatool-postgres
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: metatool
      POSTGRES_USER: metatool
      POSTGRES_PASSWORD: m3t4t00l
    ports:
      - '8432:5432'
    volumes:
      - metatool-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U metatool" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      mcp-network:

  drizzle-migrate:
    container_name: drizzle-migrate
    build:
      context: apps/metatool-app
      dockerfile: Dockerfile
      target: migrator
    command: pnpm drizzle-kit migrate
    env_file:
      - .env
    depends_on:
      metatool-postgres:
        condition: service_healthy
    networks:
      mcp-network:

  mcp-server:
    container_name: metamcp-server
    build:
      context: servers/metamcp
      dockerfile: Dockerfile
    ports:
      - "12006:12006"
    env_file:
      - .env
    networks:
      mcp-network:

volumes:
  metatool-postgres:

networks:
  mcp-network:
```

`.env`:
```
DATABASE_URL=postgresql://***:***@metatool-postgres:5432/metatool
USE_DOCKER_HOST=true
METAMCP_API_KEY=sk_mt_***
METAMCP_API_BASE_URL=http://metatool-web:12005
```

There's no indicator that the proxy is set up correctly, maybe we should add one? (check connectivity with app or vise-versa).
